### ISSUE TITLE
Support for user Dynamic VLAN

### ISSUE THREAD

**Issue by 3apa3a-b-ta3e** [maxchen021/SimpleRadius#1]
How can i easily add support for VLANs?
It`s usually saved in Tunnel-Private-Group-Id attribute of every user.

**Comment by maxchen021** [comment]
This is now possible with the 2.0 version

**Comment by 3apa3a-b-ta3e** [comment]
Great, thank you!
Will test soon, I hope

**Comment by DinkyToys** [comment]
It doesn't work standard. In the Radius config you have to alter:

copy_request_to_tunnel = yes
use_tunneled_reply = yes
proxy_tunneled_request_as_eap = yes
